spring: 
  application: 
    name: ${TENANT_GROUP:}mountain
  http: 
    converters: 
      preferred-json-mapper: jackson
    encoding:
      enabled: true
      charset: UTF-8
  servlet:
    multipart: 
      enabled: true
      file-size-threshold: 0B
      location: .
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
  jackson: #接口输出端日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  messages: 
    encoding: UTF-8
  mvc:  #WebMvcAutoConfiguration自动配置
    async: 
      request-timeout: 30000
    date-format: yyyy-MM-dd HH:mm:ss  #接口输入端日期格式,被StringDateConverter覆盖
  transaction: 
    # Default transaction timeout in seconds.
    default-timeout: 600
    rollback-on-commit-failure: true
    # 是否启用严格事务(只允许在xxxDomain.executeAction()中执行事务)
    with-strict-flag: true
  datasource: 
    # 使用druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
  kafka: 
    enabled: false
    client-id: demo # ID to pass to the server when making requests. Used for server-side logging.
    template:
      defaultTopic: trade-order
    consumer: 
      enabled: true
      bootstrap-servers: xxx.com:9091
      group-id: orderSearch
      topic: trade-order
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: latest
      fetch-max-wait: 100
      fetch-min-size: 100
      max-poll-records: 200
      heartbeat-interval: 200
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer: 
      enabled: true
      bootstrap-servers: xxx.com:9091
      topic: trade-order
      acks: 0 # 0-高吞吐量,1-均衡,all-高安全性
      batch-size: 4096
      buffer-memory: 1024KB
      compression-type: gzip # snappy消耗较低的CPU,gzip算法提高了很高的压缩比
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  task: 
    execution: 
      thread-name-prefix: task-
      pool: 
        queue-capacity: 10240
        core-size: 32
        max-size: 10240
        allow-core-thread-timeout: true
        keep-alive: 60s
    scheduling: 
      thread-name-prefix: scheduling-
      pool: 
        size: 4

server: 
  port: ${SERVER_PORT:10000}
  display-name: ${TENANT_GROUP:}mountain
  connection-timeout: 12000
  server-header: 
  servlet: 
    context-path: /
    path: /
  tomcat: 
    async-timeout: 60000
    max-connections: ${SERVER.TOMCAT.MAX-CONNECTIONS:1024}
    max-threads: ${SERVER.TOMCAT.MAX-THREADS:8}
    accept-count: ${SERVER.TOMCAT.ACCEPT-COUNT:1024}
    min-spare-threads: ${SERVER.TOMCAT.MIN-SPARE-THREADS:2}
    acceptor-thread-count: ${SERVER.TOMCAT.ACCEPTOR-THREAD-COUNT:8}
    max-http-post-size: 10000000

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${REGISTER_CENTER_DEFAULT_SERVICE_URL:http://127.0.0.1:10003/eureka/}

# Web Async
# effective是高效异步任务管理池
async: 
  effective: 
    maxPoolSize: 200
    keepAliveSeconds: 60
    queueCapacity: 2000
    corePoolSize: 100
    threadNamePrefix: EffectiveTask-
    allowCoreThreadTimeOut: true
    waitForTasksToCompleteOnShutdown: true
  # common是普通异步任务管理池
  common: 
    maxPoolSize: 20
    keepAliveSeconds: 10
    queueCapacity: 100
    corePoolSize: 5
    threadNamePrefix: CommonTask-
    allowCoreThreadTimeOut: true
    waitForTasksToCompleteOnShutdown: true

# 自定义REDIS配置
redis: 
  hostName: ${REDIS.HOST:localhost}
  #password: xxx
  port: ${REDIS.PORT:6379}
  timeout: ${REDIS.TIMEOUT:30000}
  #useSsl: false
  #dbIndex: 0
  usePool: true
  # redis pool配置
  pool: 
    maxTotal: ${REDIS.POOL.MAX_TOTAL:10}
    maxIdle: ${REDIS.POOL.MAX_IDLE:4}
    minIdle: ${REDIS.POOL.MIN_IDLE:2}
    # 空闲链接逐出配置
    # 逐出连接的最小空闲时间 1800000毫秒(30分钟)
    timeBetweenEvictionRunsMillis: 300000
    # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    minEvictableIdleTimeMillis: 1800000
    # 每次逐出检查时 逐出的最大数目
    numTestsPerEvictionRun: 3

# 数据源配置
datasource:
  # Master数据源配置
  master: 
    name: master
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:replication://${DRUID.HOST:localhost}:${DRUID.PORT:3306}/${DRUID.DATABASE:goods}?useSSL=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=true&serverTimezone=GMT%2B8
    username: ${DRUID.USERNAME:demotest}
    password: ${DRUID.PASSWORD:demotest}
    initialSize: ${DRUID.INITIAL_SIZE:4}
    maxActive: ${DRUID.MAX_ACTIVE:20}
    minIdle: ${DRUID.MIN_IDLE:4}
    maxWait: ${DRUID.MAX_WAIT:30000}
    useUnfairLock: true
    notFullTimeoutRetryCount: 2
    validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 1 #单位(秒)
    testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    testWhileIdle: true #不影响性能，并且保证安全性
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    maxPoolPreparedStatementPerConnectionSize: 10
    queryTimeout: 180 #执行查询超时时间(秒)，与MyBatis保持一致
    transactionQueryTimeout: 60 #执行事务超时时间
    timeBetweenEvictionRunsMillis: 60000 #有两个含义： 1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据
    maxEvictableIdleTimeMillis: 1800000
    minEvictableIdleTimeMillis: 600000
    removeAbandoned: true
    removeAbandonedTimeoutMillis: 300000
    filters: stat,mergeStat,slf4j,wall

# mybatis配置
mybatis: 
  master: 
    # 注意不要配置config-location
    type-aliases-package: com.github.biticcf.mountain.domain.dao.po
    type-dao-package: com.github.biticcf.mountain.domain.dao
    executorType: REUSE
    configuration: 
      cache-enabled: true
      lazy-loading-enabled: true
      aggressive-lazy-loading: false
      multiple-result-sets-enabled: true
      use-column-label: true
      use-generated-keys: true
      auto-mapping-behavior: FULL
      default-executor-type: REUSE
      default-statement-timeout: 180
      map-underscore-to-camel-case: true
      default-fetch-size: 200
      local-cache-scope: SESSION
      jdbc-type-for-null: OTHER
      lazy-load-trigger-methods: equals,clone,hashCode,toString
      log-prefix: mybatis.sql.
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    pagehelper: 
      helper-dialect: mysql
      offset-as-page-num: false
      row-bounds-with-count: true
      page-size-zero: false
      reasonable: false
      support-methods-arguments: false
      return-page-info: none

# Perform Framework
performframework: 
  # 单位ms
  threshold: 50
  # 入口配置
  entrance: 
    # proxyTargetClass: false
    interceptorNames: interceptorChain
    # 参与接口调用性能监控的类或者接口列表(支持一个*通配符),多个用英文逗号分隔
    beanNames: '*Service'
    # 在beanNames中不参与接口调用性能监控的类或者接口列表(支持一个*通配符)
    beanNamesExclude: mvcConversionService,ObjectMapper
  # 调用链配置
  chain: 
    # proxyTargetClass: false
    interceptorNames: performanceInstrumentInterceptor
    # 参与接口调用性能监控的类或者接口列表(支持一个*通配符),多个用英文逗号分隔
    beanNames: '*Domain,*Repository,*DAO,*ServiceCallback,*FeignClient'
    # 在beanNames中不参与接口调用性能监控的类或者接口列表(支持一个*通配符)
    beanNamesExclude: mvcConversionService,ObjectMapper

swagger2: 
  enable: true
